<?php

declare(strict_types=1);

namespace Modules\Core\Platform;

use App\Support\Modules\ModuleRegistry;
use Modules\Core\Events\PlatformEvent;
use ReflectionClass;

/**
 * Maps event names (as listed in module manifests) to their classes, and renders the
 * cause-and-effect catalogue (docs/event-catalogue.md).
 */
final readonly class EventCatalogue
{
    public function __construct(private ModuleRegistry $modules) {}

    /**
     * Every PlatformEvent class found in enabled modules' src/Events folders, keyed by NAME.
     *
     * @return array<string, class-string<PlatformEvent>>
     */
    public function classes(): array
    {
        $classes = [];

        foreach ($this->modules->enabled() as $module) {
            foreach (glob($module->path('src/Events/*.php')) ?: [] as $file) {
                $class = 'Modules\\'.$module->name.'\\Events\\'.basename($file, '.php');

                if (class_exists($class) && is_subclass_of($class, PlatformEvent::class) && ! (new ReflectionClass($class))->isAbstract()) {
                    $classes[$class::NAME] = $class;
                }
            }
        }

        ksort($classes);

        return $classes;
    }

    /**
     * @return list<string> Problems: declared-but-missing or present-but-undeclared events.
     */
    public function problems(): array
    {
        $problems = [];
        $classes = $this->classes();
        $declared = [];

        foreach ($this->modules->enabled() as $module) {
            foreach ($module->publishes as $name) {
                $declared[$name] = $module->name;
                if (! isset($classes[$name])) {
                    $problems[] = "{$module->name} declares [{$name}] but no event class has that NAME.";
                }
            }
            foreach ($module->consumes as $name) {
                if (! isset($classes[$name])) {
                    $problems[] = "{$module->name} consumes unknown event [{$name}].";
                }
            }
        }

        foreach (array_keys($classes) as $name) {
            if (! isset($declared[$name])) {
                $problems[] = "Event [{$name}] exists but is not declared under events.publishes in any module.json.";
            }
        }

        return $problems;
    }

    public function markdown(): string
    {
        $consumers = [];
        $publishers = [];
        foreach ($this->modules->enabled() as $module) {
            foreach ($module->publishes as $name) {
                $publishers[$name] = $module->title;
            }
            foreach ($module->consumes as $name) {
                $consumers[$name][] = $module->title;
            }
        }

        $lines = [
            '# Platform event catalogue',
            '',
            'Generated by `php artisan kasi:docs:generate` from module manifests and event classes. Do not edit by hand.',
            '',
            'Every event is written to the platform event log and can be used by any portal through listeners.',
            '',
            '| Event | Published by | Used by | What it means |',
            '|---|---|---|---|',
        ];

        foreach ($this->classes() as $name => $class) {
            $lines[] = sprintf('| `%s` | %s | %s | %s |', $name, $publishers[$name] ?? '-', implode(', ', $consumers[$name] ?? ['-']), $class::DESCRIPTION);
        }

        return implode("\n", $lines)."\n";
    }
}
