<?php

declare(strict_types=1);

namespace Modules\Core\Notifications;

use App\Support\Modules\ModuleRegistry;
use ReflectionClass;

/**
 * Every notification type, discovered from enabled modules (src/Notifications/Messages),
 * and the WhatsApp template list to submit to Meta.
 */
final readonly class NotificationCatalogue
{
    public function __construct(private ModuleRegistry $modules) {}

    /**
     * @return array<string, class-string<KasiNotification>>
     */
    public function classes(): array
    {
        $classes = [];

        foreach ($this->modules->enabled() as $module) {
            foreach (glob($module->path('src/Notifications/Messages/*.php')) ?: [] as $file) {
                $class = 'Modules\\'.$module->name.'\\Notifications\\Messages\\'.basename($file, '.php');

                if (class_exists($class) && is_subclass_of($class, KasiNotification::class) && ! (new ReflectionClass($class))->isAbstract()) {
                    $classes[$class::KEY] = $class;
                }
            }
        }

        ksort($classes);

        return $classes;
    }

    public function whatsappMarkdown(): string
    {
        $lines = [
            '# WhatsApp message templates',
            '',
            'Generated by `php artisan kasi:docs:generate`. Do not edit by hand.',
            '',
            'Business-initiated WhatsApp messages must use templates approved by Meta. Submit these through the chosen',
            'WhatsApp Business provider (approval can take several days) - in English first, then each supported language.',
            'Until a template is approved, the platform falls back to SMS for important messages.',
            '',
            '| Template | Meta category | Notification | Category | Body (English) |',
            '|---|---|---|---|---|',
        ];

        foreach ($this->classes() as $key => $class) {
            if ($class::WHATSAPP_TEMPLATE === null) {
                continue;
            }

            $lines[] = sprintf('| `%s` | %s | %s | %s | %s |', $class::WHATSAPP_TEMPLATE, $class::WHATSAPP_CATEGORY, $key, $class::CATEGORY, $class::whatsappBody());
        }

        return implode("\n", $lines)."\n";
    }
}
